### ISSUE TITLE
Question: is it possible to use selected features?

### ISSUE THREAD

**Issue by alexanderadam** [yuin/goldmark#106]
Hi @yuin,

this is rather just a question than a issue report:
Is it possible with goldmark to use less or just a single markdown feature for certain cases?

I'm asking because it could be relevant for a feature where just backticks (<code>\`foo\`</code> :arrow_right: `foo`) should be converted.

**Comment by yuin** [comment]
`goldmark.Markdown` is just a facade to provide easy way for most users.

As you can see in [here](https://github.com/yuin/goldmark/blob/master/markdown.go#L99), it performs with default parsers and default renders. Instead of this, You can create `parser.Parser` that consist of certain renderer you want.

**Comment by alexanderadam** [comment]
Awesome, thank you very much! :pray:
