### ISSUE TITLE
Provide a goldmark cmd package

### ISSUE THREAD

**Issue by qlcom** [yuin/goldmark#146]

**Comment by solderjs** [comment]
I think this is what I'm looking for as well, something like this?

```bash
go get github.com/yuin/goldmark/cmd/goldmark
goldmark --unsafe-html README.md > README.html
```

**Comment by yuin** [comment]
goldmark is standards-compliant(CommonMark and GFM). There are many CLI tools that can parse CommonMark and GFM like [pandoc](https://pandoc.org/). 

I would like to recommend that you use these awesome CLI tools.

**Comment by solderjs** [comment]
I'm actually really interested in something that's lightweight and modern and in a language that is on the up (Golang, Rust, perhaps Elixer).

I see that pandoc publishes via Github Releases, which is awesome, and means it would be a great candidate for my end goal - which is something that I can easily add to https://webinstall.dev (and recommend it as part of an online course I'm doing)... but it's just so big and has so many options and it lacks RPi support (no arm64 releases).

I'd prefer something like goldmark, especially since its what hugo uses and that's another one of the tools I'm recommending for the course.

**Comment by yuin** [comment]
If we have a goldmark command, many users would request a new feature that can not be implemented by core(in this repository) stuff.

For instance, syntax highlighting is implemented as an extension in [other repository](https://github.com/yuin/goldmark-highlighting). So I think this kind of CLI tools should be maintained a separated repository.

**Comment by tomcam** [comment]
> If we have a goldmark command, many users would request a new feature that can not be implemented by core

I **really** like how you keep goldmark manageable and avoid scope creep. And thank you, by the way, for a remarkable contribution.

**Comment by qlcom** [comment]
>  So I think this kind of CLI tools should be maintained in a separated repository.

That's a good idea. Do you want to do that?
