### ISSUE TITLE
[BUG] Parser doesn't respect newlines

### ISSUE THREAD

**Issue by droslean** [yuin/goldmark#297]
```go
	source := []byte(`
Bla bla bla bla bla bla
bla bla bla bla bla bla
	`)

	markdown := goldmark.New(
		goldmark.WithExtensions(
			meta.New(
				meta.WithStoresInDocument(),
			),
		),
	)

	document := markdown.Parser().Parse(text.NewReader(source))
	first := document.FirstChild()

	t := first.Text(source)

	fmt.Println(string(t))
```

Expected output
```
Bla bla bla bla bla bla\nbla bla bla bla bla bla
```
Instead 
```
Bla bla bla bla bla blabla bla bla bla bla bla
```

**Comment by barjoio** [comment]
@droslean This is the correct parsing behaviour for Markdown. You can put 2 spaces at the end of a line to create a line-break.

Eg:

Line 1: "foo"
Line 2: "bar"
Output: `<p>foo bar</p>`

Line 1: "foo  "
Line 2: "bar"
Output: ```
<p>foo<br>
bar</p>
```

**Comment by droslean** [comment]
@barjoio We can't expect the user to know this. Unless what you just suggested belongs to a specific markdown format that this parser doesn't accept.

**Comment by teekennedy** [comment]
@droslean In your code, the node assigned to the variable `first` is a Paragraph node containing two Text nodes. The first node has the `SoftLineBreak` flag set, indicating that it ends with a [soft line break](https://spec.commonmark.org/0.30/#soft-line-breaks), which is part of the CommonMark Spec. According to the spec, soft line breaks can be rendered as a space or a newline. Since there is ambiguity in how it should be rendered, it is stored as a flag instead of being included with the text, allowing AST transformers and renderers to decide how to handle it. So the newline is being respected, just not in the way you might have thought initially.

You can find out a lot about the information being stored in the AST by calling `Dump` on a node. Here's the output of calling `first.Dump(source, 0)` on the source from your code:

```
Paragraph {
    RawText: "Bla bla bla bla bla bla
bla bla bla bla bla bla"
    HasBlankPreviousLines: true
    Text(SoftLineBreak): "Bla bla bla bla bla bla"
    Text: "bla bla bla bla bla bla"
}
```

This shows that `first` is a `Paragraph` node containing two child `Text` nodes, the first of which has the `SoftLineBreak` flag set.

**Comment by barjoio** [comment]
> @barjoio We can't expect the user to know this. Unless what you just suggested belongs to a specific markdown format that this parser doesn't accept.

This is referenced in the official Markdown specification: https://daringfireball.net/projects/markdown/syntax#p

> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.)

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.
