### ISSUE TITLE
Support for inline footnotes

### ISSUE THREAD

**Issue by lmullen** [yuin/goldmark#47]
- [x] goldmark is fully compliant with the CommonMark. Before submitting issue, you **must** read [CommonMark spec](https://spec.commonmark.org/0.29/) and confirm your output is different from [CommonMark online demo](https://spec.commonmark.org/dingus/).

Please answer the following before submitting your issue:

1. What version of goldmark are you using? : v1.1.10 via Hugo v0.60.1
2. What version of Go are you using? : go1.13.4
3. What operating system and processor architecture are you using? : darwin/amd64

This is a feature request. Both Pandoc and Black Friday support a different version of footnotes than the one currently supported by Goldmark. Pandoc refers to them as [inline footnotes](https://pandoc.org/MANUAL.html#footnotes). The syntax looks like this:

```
This is a sentence.^[This is footnote one.] This is also a sentence.^[This will become footnote two.]
```

Would it be possible for Goldmark to support this kind of footnote?

**Comment by yuin** [comment]
@lmullen 
Certainly, It be possible to implement this kind of footnotes, But I wont add this feature as a builtin extension because I would like to keep goldmark itself simple.

goldmark is an extensible library unlike blackfriday, so you can implement this kind of footnotes as an extension by yourself.
