### ISSUE TITLE
Linkify regression

### ISSUE THREAD

**Issue by bep** [yuin/goldmark#70]
```go
package main

import (
	"bytes"
	"fmt"
	"log"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

func main() {

	markdown := goldmark.New(
		goldmark.WithExtensions(extension.Linkify),
	)
	var buf bytes.Buffer
	err := markdown.Convert([]byte(`[https://google.com](https://google.com)`), &buf)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(buf.String())
}

```

Produces

```html
<p>[<a href="https://google.com%5D(https://google.com)">https://google.com](https://google.com)</a></p>
```
https://github.com/gohugoio/hugo/issues/6649

**Comment by zzwx** [comment]
Confirming https://github.com/yuin/goldmark/commit/12851a08ba14dc1da0e56a1a893452d9ed9c527f renders

`[https://golang.org/](https://golang.org)` as 
```html
<a href="https://golang.org">https://golang.org/</a>
```
`[https://golang.org](https://golang.org)` as 
```html
<a href="https://golang.org">https://golang.org</a>
```
`[https://golang.org](https://golang.org/)`
```html
<a href="https://golang.org/">https://golang.org</a>
```
`[https://golang.org/](https://golang.org/)`
```html
<a href="https://golang.org/">https://golang.org/</a>
```

**Comment by yuin** [comment]
@bep 
@zzwx 

As I wrote in #74, I think this is also an undefined and ambiguous behavior about GFM.
I do not agree with 'defined by program works' ( to avoid this, commonmark spec was defined).

But there was nothing else to do, so I've changed goldmark to closer to GFM **implementation** .

Instead of resolving this issue, you will see other strange rendering in GFM.

[ a b http://www.google.com

is not autolinked now(You can try this in github comment editor)

Do you think this is a correct behavior? Can you explain why this is not autolinked?

This is why I do not agree with 'defined by program works'. Behavior should defined by specifications.

**Comment by bep** [comment]
@yuin I agree with you about the specification part. But in this case, the specification is obviously missing some important bits to handle the ambiguity introduced by GFM. That is unfortunate as everyone who implements this has had to have this discussion.

To me, this is a simple as:

* The examples I've seen in these issues looks obviously wrong.
* I would say that, for auto-linking, it is much better to not link when in doubt, as that gives the user an option to manually link if needed.

**Comment by yuin** [comment]
@bep, Yes you are right.

[ a b http://www.google.com

is not autolinked also looks obviously wrong.(But GFM works like it)

>I would say that, for auto-linking, it is much better to not link when in doubt, as that gives the user an option to manually link if needed.

CommonMark defines that autolink should be surrounded with '<' '>' . So I think GFM autolink should be more defensive. GFM autolink parses URL aggressively(including most punctuations). This causes many problems like above.
